[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./script/target" },
    { access = "read", path = "./broadcast"}
]
mapping = { "@openzeppelin" = "lib/openzeppelin-contracts", "murky" = "lib/murky", "foundry-devops" = "lib/foundry-devops" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
